### ISSUE TITLE
fix repo description url

### ISSUE THREAD

**Issue by dsernst** [ClimbsRocks/friendsAndSnacksAndBikes#4]
If you `Edit` this repo description and put the link in the `Website for this repository` field, it will be a clickable link 👍 
#### Current:

<img width="633" alt="screen shot 2016-05-07 at 10 31 12 pm" src="https://cloud.githubusercontent.com/assets/6340841/15096187/8e4db182-14a3-11e6-8c74-6558c15d910d.png">
#### Fixed:

<img width="618" alt="screen shot 2016-05-07 at 10 31 32 pm" src="https://cloud.githubusercontent.com/assets/6340841/15096189/96131268-14a3-11e6-9c62-7aa06457d56c.png">

**Comment by ClimbsRocks** [comment]
Fixed!
